exports.default = [
    {
        name:"技术圈",
        rss:[
            {
                name:"掘金前端",
                src:"https://rsshub.app/juejin/trending/frontend/weekly",
            },
            {
                name:"开发者头条",
                src:"https://rsshub.app/toutiao/today"
            },
            {
                name:"V2EX",
                src:"https://rsshub.app/v2ex/topics/latest"
            },
            {
                name:"极客时间",
                src:"https://rsshub.app/geektime/column/48"
            },
            {
                name:"开源中国",
                src:"https://rsshub.app/oschina/news",
            },
            {
                name:"gitLab",
                src:"https://rsshub.app/gitlab/explore/trending"
            },
            {
                name:"技术头条",
                src:"https://rsshub.app/blogread/newest"
            },
            {
                name:"hust",
                src:"https://rsshub.app/hust/auto/notice/0"
            }
        
        ]
    },{
        name:"电影",
        rss:[
            {
                name:"电影天堂",
                src:"https://rsshub.app/dytt"
            },
            {
                name:"电影首发站",
                src:"https://rsshub.app/dysfz"
            }
        ]
    },
    {
        name:"新闻圈",
        rss:[
            {
                name:"南方周末-科技",
                src:"https://rsshub.app/infzm/13"
            }
        ]
    }
]